import {
  Flame,
  Home,
  Shield,
  Droplet,
  Infinity as InfinityIcon,
  Moon,
  Sparkles,
  BookOpenText,
  Users,
  Star,
  Compass,
  Heart,
  Gem,
  Gavel,
  Orbit,
  Award,
  GraduationCap,
  Landmark,
  ScrollText,
  MapPin,
  Map,
  Flower2,
  Mail,
  Phone,
  MessageCircle,
  type LucideIcon,
} from 'lucide-react'

const map: Record<string, LucideIcon> = {
  flame: Flame,
  home: Home,
  shield: Shield,
  droplet: Droplet,
  infinity: InfinityIcon,
  moon: Moon,
  sparkles: Sparkles,
  book: BookOpenText,
  users: Users,
  star: Star,
  compass: Compass,
  heart: Heart,
  gem: Gem,
  gavel: Gavel,
  orbit: Orbit,
  award: Award,
  graduation: GraduationCap,
  university: Landmark,
  scroll: ScrollText,
  pin: MapPin,
  map: Map,
  flower: Flower2,
  om: Sparkles,
  mail: Mail,
  phone: Phone,
  whatsapp: MessageCircle,
}

export function ServiceIcon({ name, className }: { name: string; className?: string }) {
  const Icon = map[name] ?? Sparkles
  return <Icon className={className} aria-hidden="true" />
}
